---

- name: Configure Apache (RedHat).
  lineinfile: >
    dest={{ apache_server_root }}/conf/{{ apache_daemon }}.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }
  - {
    regexp: "^NameVirtualHost ",
    line: "NameVirtualHost *:{{ apache_listen_port }}"
  }
  notify: restart apache
