---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Apache is installed (Debian).
  apt: >
    name={{ item }}
    state=installed
  with_items: apache_packages
  when: ansible_os_family == 'Debian'

- name: Ensure Apache is installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo={{ apache_enablerepo }}
  with_items: apache_packages
  when: ansible_os_family == 'RedHat'

- name: Ensure Apache is started and enabled on boot.
  service: >
    name={{ apache_daemon }}
    state=started
    enabled=yes
